"""
Chat schemas
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Single chat message"""
    role: str = Field(..., description="Message role: 'human' or 'ai'")
    content: str = Field(..., description="Message content")


class ChatRequest(BaseModel):
    """Chat request schema"""
    question: str = Field(..., min_length=1, description="User's question")
    user_id: Optional[str] = Field(
        default=None,
        description="Unique anonymous user ID (generated by client)"
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID for grouping conversations"
    )
    chat_history: Optional[List[ChatMessage]] = Field(
        default=None,
        description="Previous chat messages for context"
    )
    k: int = Field(
        default=5,
        ge=1,
        le=20,
        description="Number of documents to retrieve (1-20)"
    )
    use_memory: bool = Field(
        default=True,
        description="Whether to search memory for similar past conversations"
    )
    store_in_memory: bool = Field(
        default=True,
        description="Whether to store this conversation in memory"
    )


class SourceInfo(BaseModel):
    """Source information"""
    source: str
    page: str
    content_preview: str


class ChatResponse(BaseModel):
    """Chat response schema"""
    answer: str = Field(..., description="AI's answer")
    sources: List[SourceInfo] = Field(..., description="Sources used for the answer")
    context_used: int = Field(..., description="Number of documents used")
    quick_suggestions: List[str] = Field(
        default=[],
        description="Quick follow-up question suggestions"
    )
    memory_used: bool = Field(
        default=False,
        description="Whether memory was used for context"
    )
    user_id: Optional[str] = Field(
        default=None,
        description="The anonymous user ID used for this request"
    )
    session_id: Optional[str] = Field(
        default=None,
        description="The session ID used for this request"
    )
    contextualized_query: Optional[str] = Field(
        default=None,
        description="The rewritten query used for retrieval (for follow-up questions)"
    )
    error: Optional[str] = Field(default=None, description="Error message if any")


class MemoryStats(BaseModel):
    """Memory statistics"""
    total_conversations: int
    index_size: int
    total_users: Optional[int] = 0
    index_fullness: Optional[float] = None  # Pinecone only
    dimension: Optional[int] = None  # Pinecone only


class UserStats(BaseModel):
    """User-specific statistics"""
    user_id: str
    exists: bool
    conversation_count: int = 0
    first_seen: Optional[str] = None
    last_seen: Optional[str] = None
    session_count: int = 0

